(setq config-dir "~/.emacs.d.default")
(load (concat config-dir "/configs.el"))
(load (concat config-dir "/custom.el"))
(load (concat config-dir "/ritho-theme.el"))

(load (concat config-dir "/env.el"))
(load (concat config-dir "/project.el"))
(load (concat config-dir "/flycheck.el"))
(load (concat config-dir "/autocomplete.el"))
(load (concat config-dir "/flyspell.el"))
(load (concat config-dir "/yasnippet.el"))
;; (load (concat config-dir "/elixir.el"))
(load (concat config-dir "/ritho-modes.el"))
(load (concat config-dir "/org-mode.el"))
;; (load (concat config-dir "/org-gtd.el"))
(load (concat config-dir "/mail-mu4e.el"))
(load (concat config-dir "/mark-multiple.el"))
;; (load (concat config-dir "/less-mode.el"))
(load (concat config-dir "/go-mode.el"))
;; (load (concat config-dir "/perl-mode.el"))
(load (concat config-dir "/python.el"))
(load (concat config-dir "/latex.el"))
(load (concat config-dir "/markdown.el"))
(load (concat config-dir "/word-count.el"))
(load (concat config-dir "/php.el"))
(load (concat config-dir "/magit.el"))
;; (load (concat config-dir "/gitlab.el"))
;; (load (concat config-dir "/howm.el"))
(load (concat config-dir "/asciidoc.el"))
(load (concat config-dir "/json.el"))
;; (load (concat config-dir "/exwm.el"))
;; (load (concat config-dir "/ews.el"))
(load (concat config-dir "/git-functions.el"))
(load (concat config-dir "/gpt.el"))
(load (concat config-dir "/copilot-configs.el"))
(load (concat config-dir "/codeium-config.el"))

(load (concat config-dir "/secrets.el"))
(load-theme 'ritho)
(put 'upcase-region 'disabled nil)
