(load "~/.emacs.d/configs.el")
(load "~/.emacs.d/custom.el")
(load "~/.emacs.d/ritho-theme.el")

(load "~/.emacs.d/flycheck.el")
(load "~/.emacs.d/autocomplete.el")
(load "~/.emacs.d/flyspell.el")
(load "~/.emacs.d/yasnippet.el")
;; (load "~/.emacs.d/elixir.el")
(load "~/.emacs.d/ritho-modes.el")
(load "~/.emacs.d/org-mode.el")
;; (load "~/.emacs.d/org-gtd.el")
(load "~/.emacs.d/mail-mu4e.el")
(load "~/.emacs.d/mark-multiple.el")
(load "~/.emacs.d/less-mode.el")
(load "~/.emacs.d/go-mode.el")
(load "~/.emacs.d/perl-mode.el")
(load "~/.emacs.d/latex.el")
(load "~/.emacs.d/markdown.el")
(load "~/.emacs.d/word-count.el")
(load "~/.emacs.d/pocket.el")
(load "~/.emacs.d/php.el")
(load "~/.emacs.d/magit.el")
(load "~/.emacs.d/gitlab.el")
(load "~/.emacs.d/howm.el")
(load "~/.emacs.d/asciidoc.el")

(load "~/.emacs.d/secrets.el")
(load-theme 'ritho)
(put 'upcase-region 'disabled nil)
