(load (concat (getenv "PWD") "/configs.el"))
(load (concat (getenv "PWD") "/custom.el"))
(load (concat (getenv "PWD") "/ritho-theme.el"))

(load (concat (getenv "PWD") "/project.el"))
(load (concat (getenv "PWD") "/flycheck.el"))
(load (concat (getenv "PWD") "/autocomplete.el"))
(load (concat (getenv "PWD") "/flyspell.el"))
(load (concat (getenv "PWD") "/yasnippet.el"))
;; (load (concat (getenv "PWD") "/elixir.el"))
(load (concat (getenv "PWD") "/ritho-modes.el"))
(load (concat (getenv "PWD") "/org-mode.el"))
;; (load (concat (getenv "PWD") "/org-gtd.el"))
(load (concat (getenv "PWD") "/mail-mu4e.el"))
(load (concat (getenv "PWD") "/mark-multiple.el"))
;; (load (concat (getenv "PWD") "/less-mode.el"))
(load (concat (getenv "PWD") "/go-mode.el"))
;; (load (concat (getenv "PWD") "/perl-mode.el"))
(load (concat (getenv "PWD") "/python.el"))
(load (concat (getenv "PWD") "/latex.el"))
(load (concat (getenv "PWD") "/markdown.el"))
(load (concat (getenv "PWD") "/word-count.el"))
(load (concat (getenv "PWD") "/php.el"))
(load (concat (getenv "PWD") "/magit.el"))
;; (load (concat (getenv "PWD") "/gitlab.el"))
;; (load (concat (getenv "PWD") "/howm.el"))
(load (concat (getenv "PWD") "/asciidoc.el"))
(load (concat (getenv "PWD") "/json.el"))
;; (load (concat (getenv "PWD") "/exwm.el"))
;; (load (concat (getenv "PWD") "/ews.el"))
(load (concat (getenv "PWD") "/git-functions.el"))
(load (concat (getenv "PWD") "/gpt.el"))

(load (concat (getenv "PWD") "/secrets.el"))
(add-to-list 'custom-theme-load-path (getenv "PWD"))
(load-theme 'ritho)
(put 'upcase-region 'disabled nil)
