;; Use cperl-mode instead of the default perl-mode
(add-to-list 'auto-mode-alist '("\\.\\([pP][Llm]\\|al\\)\\'" . cperl-mode))
(add-to-list 'interpreter-mode-alist '("perl" . cperl-mode))
(add-to-list 'interpreter-mode-alist '("perl5" . cperl-mode))
(add-to-list 'interpreter-mode-alist '("miniperl" . cperl-mode))

(add-hook 'cperl-mode-hook 'n-cperl-mode-hook t)
(defun n-cperl-mode-hook ()
  (setq cperl-indent-level 8)
  (setq cperl-continued-statement-offset 0)
  (setq cperl-extra-newline-before-brace t)
  ;; (set-face-background 'cperl-array-face ((t (:foreground "green" :weight bold))))
  ;; (set-face-background 'cperl-hash-face ((t (:foreground "Red" :slant italic :weight bold))))
  (linum-mode 1)
  )
